name: speech-mc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03=py36_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py36he11e457_0
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py36_0
  - alabaster=0.7.12=py36_0
  - anaconda=custom=py36_1
  - anaconda-client=1.7.2=py36_0
  - anaconda-navigator=1.8.7=py36_0
  - anaconda-project=0.8.4=py_0
  - argh=0.26.2=py36_0
  - asn1crypto=1.3.0=py36_0
  - astor=0.8.0=py36_0
  - astroid=2.3.3=py36_0
  - astropy=3.2.3=py36h7b6447c_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.3.0=py_0
  - audioread=2.1.5=py36_0
  - autopep8=1.4.4=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py36_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports.os=0.1.1=py36_0
  - backports.shutil_get_terminal_size=1.0.0=py36_2
  - backports.tempfile=1.0=py_1
  - backports.weakref=1.0.post1=py_1
  - beautifulsoup4=4.8.2=py36_0
  - bitarray=1.2.1=py36h7b6447c_0
  - bkcharts=0.2=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - blosc=1.16.3=hd408876_0
  - bokeh=2.0.0=py36_0
  - boto=2.49.0=py36_0
  - bottleneck=1.3.2=py36heb32a55_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - cffi=1.14.0=py36h2e261b9_0
  - chardet=3.0.4=py36_1003
  - click=7.1.1=py_0
  - cloudpickle=1.3.0=py_0
  - clyent=1.2.2=py36_1
  - colorama=0.4.3=py_0
  - conda-package-handling=1.6.0=py36h7b6447c_0
  - conda-verify=3.4.2=py_1
  - contextlib2=0.6.0.post1=py_0
  - cryptography=2.8=py36h1ba5d50_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.6.5=cuda9.0_0
  - cupti=9.0.176=0
  - curl=7.69.1=hbc83047_0
  - cycler=0.10.0=py36_0
  - cython=0.29.15=py36he6710b0_0
  - cytoolz=0.10.1=py36h7b6447c_0
  - dask=2.12.0=py_0
  - dask-core=2.12.0=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20181111=py_0
  - distributed=2.12.0=py36_0
  - docutils=0.16=py36_0
  - entrypoints=0.3=py36_0
  - et_xmlfile=1.0.1=py36_0
  - expat=2.2.6=he6710b0_0
  - fastcache=1.1.0=py36h7b6447c_0
  - ffmpeg=2.8.6=hf82bc7d_7
  - filelock=3.0.12=py_0
  - flake8=3.7.9=py36_0
  - flask=1.1.1=py_1
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - fsspec=0.6.3=py_0
  - future=0.18.2=py36_0
  - gast=0.3.3=py_0
  - get_terminal_size=1.0.0=haa9412d_0
  - gevent=1.4.0=py36h7b6447c_0
  - glib=2.63.1=h5a9c865_0
  - glob2=0.7=py_0
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py36h10f8cd9_2
  - graphite2=1.3.13=h23475e2_0
  - greenlet=0.4.15=py36h7b6447c_0
  - grpcio=1.27.2=py36hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py36h7918eee_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.1=py_0
  - html5lib=1.0.1=py36_0
  - hypothesis=5.5.4=py_0
  - icu=58.2=h9c2bf20_1
  - idna=2.9=py_1
  - imageio=2.8.0=py_0
  - imagesize=1.2.0=py_0
  - importlib_metadata=1.5.0=py36_0
  - intel-openmp=2019.4=243
  - intervaltree=3.0.2=py_0
  - ipykernel=5.1.4=py36h39e3cac_0
  - ipython=7.13.0=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py36_0
  - itsdangerous=1.1.0=py36_0
  - jbig=2.1=hdba287a_0
  - jdcal=1.4.1=py_0
  - jedi=0.15.2=py36_0
  - jeepney=0.4.3=py_0
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.3=py_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=6.0.0=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.1=py36_0
  - jupyterlab=1.2.6=pyhf63ae98_0
  - jupyterlab_server=1.0.7=py_0
  - keyring=21.1.0=py36_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - krb5=1.17.1=h173b8e3_0
  - lazy-object-proxy=1.4.3=py36h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libflac=1.3.1=0
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h63c8f33_5
  - libogg=1.3.2=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.4=hd408876_0
  - librosa=0.6.2=py_0
  - libsndfile=1.0.28=hfc679d8_0
  - libsodium=1.0.16=h1bed415_0
  - libspatialindex=1.9.3=he6710b0_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libtool=2.4.6=h7b6447c_5
  - libuuid=1.0.3=h1bed415_2
  - libvorbis=1.3.6=h7b6447c_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - llvmlite=0.31.0=py36hd408876_0
  - locket=0.2.0=py36_1
  - lxml=4.5.0=py36hefd8a0e_0
  - lz4-c=1.8.1.2=h14c3975_0
  - lzo=2.10=h49e0be7_2
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2018.0.3=1
  - mkl-service=1.1.2=py36h90e4bf4_5
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - mock=4.0.1=py_0
  - more-itertools=8.2.0=py_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.1=hdf1c602_3
  - mpmath=1.1.0=py36_0
  - msgpack-python=0.6.1=py36hfd86e86_1
  - multipledispatch=0.6.0=py36_0
  - navigator-updater=0.2.1=py36_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.0.4=py_0
  - nccl=1.3.5=cuda9.0_0
  - ncurses=6.2=he6710b0_0
  - networkx=2.4=py_0
  - ninja=1.9.0=py36hfd86e86_0
  - nltk=3.4.5=py36_0
  - nose=1.3.7=py36_2
  - notebook=6.0.3=py36_0
  - numba=0.48.0=py36h0573a6f_0
  - numexpr=2.6.8=py36hd89afb7_0
  - numpy=1.15.4=py36h1d66e8a_0
  - numpy-base=1.15.4=py36h81de0dd_0
  - numpydoc=0.9.2=py_0
  - olefile=0.46=py36_0
  - openpyxl=3.0.3=py_0
  - openssl=1.1.1g=h516909a_0
  - packaging=20.3=py_0
  - pandas=1.0.3=py36h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - pango=1.42.4=h049681c_0
  - parso=0.5.2=py_0
  - partd=1.1.0=py_0
  - patchelf=0.10=he6710b0_0
  - path=13.1.0=py36_0
  - path.py=12.4.0=0
  - pathlib2=2.3.5=py36_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.1=py36_0
  - pcre=8.43=he6710b0_0
  - pep8=1.7.1=py36_0
  - pexpect=4.8.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.0.0=py36hb39fc2d_0
  - pip=20.0.2=py36_1
  - pixman=0.38.0=h7b6447c_0
  - pkginfo=1.5.0.1=py36_0
  - pluggy=0.13.1=py36_0
  - ply=3.11=py36_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - protobuf=3.11.4=py36he6710b0_0
  - psutil=5.7.0=py36h7b6447c_0
  - ptyprocess=0.6.0=py36_0
  - pudb=2018.1=py36_1000
  - py=1.8.1=py_0
  - pycodestyle=2.5.0=py36_0
  - pycosat=0.6.3=py36h7b6447c_0
  - pycparser=2.20=py_0
  - pycrypto=2.6.1=py36h14c3975_9
  - pycurl=7.43.0.5=py36h1ba5d50_0
  - pydocstyle=4.0.1=py_0
  - pydot=1.2.4=py36_0
  - pyflakes=2.1.1=py36_0
  - pygments=2.6.1=py_0
  - pylint=2.4.4=py36_0
  - pyodbc=4.0.30=py36he6710b0_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.15.7=py36h7b6447c_0
  - pysocks=1.7.1=py36_0
  - pysoundfile=0.10.1=py_0
  - pytables=3.6.1=py36h71ec239_0
  - pytest=5.4.1=py36_0
  - pytest-arraydiff=0.3=py36h39e3cac_0
  - pytest-astropy=0.8.0=py_0
  - pytest-astropy-header=0.1.2=py_0
  - pytest-doctestplus=0.5.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.2=py36_0
  - python=3.6.10=h191fe78_1
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.3.4=py_0
  - python-language-server=0.31.9=py36_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.1.0=py3.6_cuda9.0.176_cudnn7.5.1_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36h7b6447c_0
  - pyxdg=0.26=py_0
  - pyyaml=5.3.1=py36h7b6447c_0
  - pyzmq=18.1.1=py36he6710b0_0
  - qdarkstyle=2.8=py_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=0.7.0=py_0
  - qtconsole=4.7.1=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - requests=2.23.0=py36_0
  - resampy=0.2.1=py_1
  - rope=0.16.0=py_0
  - rtree=0.9.3=py36_0
  - ruamel_yaml=0.15.87=py36h7b6447c_0
  - scikit-image=0.16.2=py36h0573a6f_0
  - scikit-learn=0.20.1=py36h4989274_0
  - scipy=1.1.0=py36hfa4b5c9_1
  - seaborn=0.10.0=py_0
  - secretstorage=3.1.2=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=46.1.1=py36_0
  - simplegeneric=0.8.1=py36_2
  - singledispatch=3.4.0.3=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.14.0=py36_0
  - snappy=1.1.7=hbae5bb6_3
  - snowballstemmer=2.0.0=py_0
  - sortedcollections=1.1.2=py36_0
  - sortedcontainers=2.1.0=py36_0
  - soupsieve=2.0=py_0
  - sphinx=2.4.0=py_0
  - sphinxcontrib=1.0=py36_1
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sphinxcontrib-websupport=1.2.0=py_0
  - spyder=4.1.1=py36_1
  - spyder-kernels=1.9.0=py36_0
  - sqlalchemy=1.3.15=py36h7b6447c_1
  - sqlite=3.31.1=h7b6447c_0
  - statsmodels=0.11.0=py36h7b6447c_0
  - sympy=1.5.1=py36_0
  - tbb=2020.0=hfd86e86_0
  - tbb4py=2020.0=py36hfd86e86_0
  - tblib=1.6.0=py_0
  - tensorboard=1.9.0=py36hf484d3e_0
  - tensorflow=1.9.0=gpu_py36h02c5d5e_1
  - tensorflow-base=1.9.0=gpu_py36h6ecc378_0
  - tensorflow-gpu=1.9.0=hf154084_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.3.0=py36_cu9.0.176_1
  - tornado=6.0.4=py36h7b6447c_1
  - tqdm=4.43.0=py_0
  - traitlets=4.3.3=py36_0
  - typed-ast=1.4.1=py36h7b6447c_0
  - typing_extensions=3.7.4.1=py36_0
  - ujson=1.35=py36h14c3975_0
  - umap-learn=0.4.1=py36h9f0ad1d_1
  - unicodecsv=0.14.1=py36_0
  - unixodbc=2.3.7=h14c3975_0
  - urllib3=1.25.8=py36_0
  - urwid=1.3.1=py36_1000
  - watchdog=0.10.2=py36_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py36_1
  - werkzeug=1.0.0=py_0
  - wheel=0.34.2=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - wrapt=1.12.1=py36h7b6447c_1
  - wurlitzer=2.0.0=py36_0
  - x264=1!152.20180806=h7b6447c_0
  - xlrd=1.2.0=py36_0
  - xlsxwriter=1.2.8=py_0
  - xlwt=1.3.0=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - yapf=0.28.0=py_0
  - zeromq=4.3.1=he6710b0_3
  - zict=2.0.0=py_0
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - comet-git-pure==0.19.16
    - comet-ml==3.1.6
    - configobj==5.0.6
    - dill==0.3.1.1
    - everett==1.0.2
    - jsonpatch==1.25
    - jsonpointer==2.0
    - jsonschema==3.0.2
    - multiprocess==0.70.9
    - netifaces==0.10.9
    - nvidia-ml-py3==7.352.0
    - torchfile==0.1.0
    - torchsummary==1.5.1
    - umap==0.1.1
    - visdom==0.1.8.9
    - webrtcvad==2.0.10
    - websocket-client==0.57.0
prefix: /home/ml/c.onu/anaconda3/envs/speech-mc

